// <auto-generated />
using Animal.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Animal.Migrations
{
    [DbContext(typeof(AnimalContext))]
    [Migration("20190611082307_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Animal.Models.feedFooder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address");

                    b.Property<string>("adl");

                    b.Property<string>("c");

                    b.Property<string>("cp");

                    b.Property<string>("cultivation");

                    b.Property<string>("df");

                    b.Property<string>("district");

                    b.Property<string>("dm");

                    b.Property<string>("fooderNameEng");

                    b.Property<string>("fooderNameNep");

                    b.Property<string>("grassProduct");

                    b.Property<string>("municipility");

                    b.Property<string>("ndf");

                    b.Property<string>("nitrateScore");

                    b.Property<string>("p");

                    b.Property<string>("price");

                    b.Property<string>("remarks");

                    b.Property<string>("seedHarvestingStorage");

                    b.Property<string>("seedingMethod");

                    b.Property<string>("shortNote");

                    b.Property<string>("state");

                    b.Property<string>("tanni");

                    b.Property<string>("tdn");

                    b.HasKey("id");

                    b.ToTable("dbug_feedFooder");
                });
#pragma warning restore 612, 618
        }
    }
}
